{
  "language": "python",
  "python": "3.5",
  "python": "3.6",
  "install": [
    "pip install -r requirements.txt"
  ],
  "script": [
    "pytest"
  ],
  "group": "stable",
  "dist": "xenial",
  "os": "linux"
}

